/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CacheConfigSpecApplyConfiguration represents a declarative configuration of the CacheConfigSpec type for use
// with apply.
type CacheConfigSpecApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Path     *string `json:"path,omitempty"`
	KeysZone *string `json:"keysZone,omitempty"`
	Inactive *string `json:"inactive,omitempty"`
	MaxSize  *string `json:"maxSize,omitempty"`
}

// CacheConfigSpecApplyConfiguration constructs a declarative configuration of the CacheConfigSpec type for use with
// apply.
func CacheConfigSpec() *CacheConfigSpecApplyConfiguration {
	return &CacheConfigSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CacheConfigSpecApplyConfiguration) WithName(value string) *CacheConfigSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *CacheConfigSpecApplyConfiguration) WithPath(value string) *CacheConfigSpecApplyConfiguration {
	b.Path = &value
	return b
}

// WithKeysZone sets the KeysZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeysZone field is set to the value of the last call.
func (b *CacheConfigSpecApplyConfiguration) WithKeysZone(value string) *CacheConfigSpecApplyConfiguration {
	b.KeysZone = &value
	return b
}

// WithInactive sets the Inactive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inactive field is set to the value of the last call.
func (b *CacheConfigSpecApplyConfiguration) WithInactive(value string) *CacheConfigSpecApplyConfiguration {
	b.Inactive = &value
	return b
}

// WithMaxSize sets the MaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSize field is set to the value of the last call.
func (b *CacheConfigSpecApplyConfiguration) WithMaxSize(value string) *CacheConfigSpecApplyConfiguration {
	b.MaxSize = &value
	return b
}
