/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LocationSpecApplyConfiguration represents a declarative configuration of the LocationSpec type for use
// with apply.
type LocationSpecApplyConfiguration struct {
	FallbackLocations []string                          `json:"fallbackLocations,omitempty"`
	Nodes             []NodeSpecApplyConfiguration      `json:"nodes,omitempty"`
	GeoLookup         *GeoLookupSpecApplyConfiguration  `json:"geoLookup,omitempty"`
	MaintenanceMode   *bool                             `json:"maintenanceMode,omitempty"`
	NodeGroups        []NodeGroupSpecApplyConfiguration `json:"nodeGroups,omitempty"`
}

// LocationSpecApplyConfiguration constructs a declarative configuration of the LocationSpec type for use with
// apply.
func LocationSpec() *LocationSpecApplyConfiguration {
	return &LocationSpecApplyConfiguration{}
}

// WithFallbackLocations adds the given value to the FallbackLocations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FallbackLocations field.
func (b *LocationSpecApplyConfiguration) WithFallbackLocations(values ...string) *LocationSpecApplyConfiguration {
	for i := range values {
		b.FallbackLocations = append(b.FallbackLocations, values[i])
	}
	return b
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *LocationSpecApplyConfiguration) WithNodes(values ...*NodeSpecApplyConfiguration) *LocationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodes")
		}
		b.Nodes = append(b.Nodes, *values[i])
	}
	return b
}

// WithGeoLookup sets the GeoLookup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GeoLookup field is set to the value of the last call.
func (b *LocationSpecApplyConfiguration) WithGeoLookup(value *GeoLookupSpecApplyConfiguration) *LocationSpecApplyConfiguration {
	b.GeoLookup = value
	return b
}

// WithMaintenanceMode sets the MaintenanceMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceMode field is set to the value of the last call.
func (b *LocationSpecApplyConfiguration) WithMaintenanceMode(value bool) *LocationSpecApplyConfiguration {
	b.MaintenanceMode = &value
	return b
}

// WithNodeGroups adds the given value to the NodeGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeGroups field.
func (b *LocationSpecApplyConfiguration) WithNodeGroups(values ...*NodeGroupSpecApplyConfiguration) *LocationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodeGroups")
		}
		b.NodeGroups = append(b.NodeGroups, *values[i])
	}
	return b
}
