/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LocationStatusApplyConfiguration represents a declarative configuration of the LocationStatus type for use
// with apply.
type LocationStatusApplyConfiguration struct {
	Status     *string                                         `json:"status,omitempty"`
	NodeStatus map[string]NodeInstanceStatusApplyConfiguration `json:"nodeStatus,omitempty"`
}

// LocationStatusApplyConfiguration constructs a declarative configuration of the LocationStatus type for use with
// apply.
func LocationStatus() *LocationStatusApplyConfiguration {
	return &LocationStatusApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *LocationStatusApplyConfiguration) WithStatus(value string) *LocationStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithNodeStatus puts the entries into the NodeStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeStatus field,
// overwriting an existing map entries in NodeStatus field with the same key.
func (b *LocationStatusApplyConfiguration) WithNodeStatus(entries map[string]NodeInstanceStatusApplyConfiguration) *LocationStatusApplyConfiguration {
	if b.NodeStatus == nil && len(entries) > 0 {
		b.NodeStatus = make(map[string]NodeInstanceStatusApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.NodeStatus[k] = v
	}
	return b
}
