/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NodeGroupSpecApplyConfiguration represents a declarative configuration of the NodeGroupSpec type for use
// with apply.
type NodeGroupSpecApplyConfiguration struct {
	Name         *string                            `json:"name,omitempty"`
	Nodes        []NodeSpecApplyConfiguration       `json:"nodes,omitempty"`
	CacheConfig  *CacheConfigSpecApplyConfiguration `json:"cacheConfig,omitempty"`
	NodeSelector map[string]string                  `json:"nodeSelector,omitempty"`
}

// NodeGroupSpecApplyConfiguration constructs a declarative configuration of the NodeGroupSpec type for use with
// apply.
func NodeGroupSpec() *NodeGroupSpecApplyConfiguration {
	return &NodeGroupSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NodeGroupSpecApplyConfiguration) WithName(value string) *NodeGroupSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *NodeGroupSpecApplyConfiguration) WithNodes(values ...*NodeSpecApplyConfiguration) *NodeGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodes")
		}
		b.Nodes = append(b.Nodes, *values[i])
	}
	return b
}

// WithCacheConfig sets the CacheConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheConfig field is set to the value of the last call.
func (b *NodeGroupSpecApplyConfiguration) WithCacheConfig(value *CacheConfigSpecApplyConfiguration) *NodeGroupSpecApplyConfiguration {
	b.CacheConfig = value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *NodeGroupSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *NodeGroupSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
