/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NodeSpecApplyConfiguration represents a declarative configuration of the NodeSpec type for use
// with apply.
type NodeSpecApplyConfiguration struct {
	Name            *string  `json:"name,omitempty"`
	Ipv4            *string  `json:"ipv4,omitempty"`
	Ipv6            *string  `json:"ipv6,omitempty"`
	Caches          []string `json:"caches,omitempty"`
	MaintenanceMode *bool    `json:"maintenanceMode,omitempty"`
}

// NodeSpecApplyConfiguration constructs a declarative configuration of the NodeSpec type for use with
// apply.
func NodeSpec() *NodeSpecApplyConfiguration {
	return &NodeSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithName(value string) *NodeSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithIpv4 sets the Ipv4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ipv4 field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithIpv4(value string) *NodeSpecApplyConfiguration {
	b.Ipv4 = &value
	return b
}

// WithIpv6 sets the Ipv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ipv6 field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithIpv6(value string) *NodeSpecApplyConfiguration {
	b.Ipv6 = &value
	return b
}

// WithCaches adds the given value to the Caches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Caches field.
func (b *NodeSpecApplyConfiguration) WithCaches(values ...string) *NodeSpecApplyConfiguration {
	for i := range values {
		b.Caches = append(b.Caches, values[i])
	}
	return b
}

// WithMaintenanceMode sets the MaintenanceMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceMode field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithMaintenanceMode(value bool) *NodeSpecApplyConfiguration {
	b.MaintenanceMode = &value
	return b
}
