# This rule is not used by the project edgecdnx-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the infrastructure.edgecdnx.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edgecdnx-controller
    app.kubernetes.io/managed-by: kustomize
  name: prefixlist-editor-role
rules:
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - prefixlists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - prefixlists/status
  verbs:
  - get
