---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - acme.cert-manager.io/v1
  resources:
  - challenges
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acme.cert-manager.io/v1
  resources:
  - challenges/status
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io/v1
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations
  - prefixlists
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations/finalizers
  - prefixlists/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations/status
  - prefixlists/status
  - services/status
  verbs:
  - get
  - patch
  - update
