# This rule is not used by the project edgecdnx-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infrastructure.edgecdnx.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edgecdnx-controller
    app.kubernetes.io/managed-by: kustomize
  name: service-admin-role
rules:
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - services/status
  verbs:
  - get
