# This rule is not used by the project edgecdnx-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infrastructure.edgecdnx.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edgecdnx-controller
    app.kubernetes.io/managed-by: kustomize
  name: service-viewer-role
rules:
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - services/status
  verbs:
  - get
