apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Zone
metadata:
  name: edgecdnx-com
spec:
  zone: edgecdnx.com
  email: noc.edgecdnx.com.
---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Zone
metadata:
  name: example-com
spec:
  zone: example.com
  email: noc.example.com.
