apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Location
metadata:
  labels:
    app.kubernetes.io/name: edgecdnx-controller
    app.kubernetes.io/managed-by: kustomize
  name: location-sample
spec:
  # TODO(user): Add fields here
