name: Build and Push Docker Image
on:
  workflow_run:
    workflows: ["E2E Tests"]
    branches: [main]
    tags:
      - 'v*'
    types: 
      - completed

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            export IMG="fr6nco/edgecdnx-controller:${GITHUB_REF_NAME}"
          else
            export IMG="fr6nco/edgecdnx-controller:latest"
          fi
          make docker-buildx